FROM mcr.microsoft.com/dotnet/aspnet:5.0-focal AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# ENV ASPNETCORE_URLS=https://localhost:5001;http://localhost:5000
ENV SimpleProperty="hello-from-BASE-dockerfile"

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:5.0-focal AS build
WORKDIR /src
COPY ["CavedRockCode.Api/CavedRockCode.Api.csproj", "CavedRockCode.Api/"]
RUN dotnet restore "CavedRockCode.Api/CavedRockCode.Api.csproj"
#COPY ["CavedRockCode.Api.csproj", "./"]
#RUN dotnet restore "CavedRockCode.Api.csproj"
COPY . .
WORKDIR "/src/CavedRockCode.Api"
#WORKDIR "/src/."
RUN dotnet build "CavedRockCode.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CavedRockCode.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV SimpleProperty="hello-from-FINAL-dockerfile"
ENTRYPOINT ["dotnet", "CavedRockCode.Api.dll"]
